#!/bin/bash
USERENV=$1
ENV=$1
BASEDIR=$(dirname "$0")
#echo "$BASEDIR"
CONFFILENAME="$BASEDIR/token.properties"
cp $BASEDIR/token.properties.template $BASEDIR/token.properties
echo $CONFFILENAME
#source sourcevar.sh
AUTH0_ID=$(eval "echo \$${ENV}_AUTH0_ID")
AUTH0_ID_SECRET=$(eval "echo \$${ENV}_AUTH0_ID_SECRET")
AUTH0_NONINTERACTIVE_ID=$(eval "echo \$${ENV}_AUTH0_NONINTERACTIVE_ID")
AUTH0_NONINTERACTIVE_ID_SECRET=$(eval "echo \$${ENV}_AUTH0_NONINTERACTIVE_ID_SECRET")
AUTH0_NEW_ID=$(eval "echo \$${ENV}_AUTH0_NEW_ID")
AUTH0_NEW_ID_SECRET=$(eval "echo \$${ENV}_AUTH0_NEW_ID_SECRET")
AUTH0_NEW_NONINTERACTIVE_ID=$(eval "echo \$${ENV}_AUTH0_NEW_NONINTERACTIVE_ID")
AUTH0_NEW_NONINTERACTIVE_ID_SECRET=$(eval "echo \$${ENV}_AUTH0_NEW_NONINTERACTIVE_ID_SECRET")
DICEAUTH_DICE_URL=$(eval "echo \$${ENV}_DICEAUTH_DICE_URL")
DICEAUTH_API_KEY=$(eval "echo \$${ENV}_DICEAUTH_API_KEY")
DICEAUTH_CREDDEFID=$(eval "echo \$${ENV}_DICEAUTH_CREDDEFID")
ZENDESK_ID=$(eval "echo \$${ENV}_ZENDESK_ID")
SERVICEACC02_UID=$(eval "echo \$${ENV}_SERVICEACC02_UID")
AUTH_SECRET=$(eval "echo \$${ENV}_AUTH_SECRET")

EVENTBUSSERVICE_ENDPOINT=$(eval "echo \$${ENV}_EVENTBUSSERVICE_ENDPOINT")
EVENTBUSSERVICE_TOPIC=$(eval "echo \$${ENV}_EVENTBUSSERVICE_TOPIC")
EVENTBUSSERVICE_ORIGINATOR=$(eval "echo \$${ENV}_EVENTBUSSERVICE_ORIGINATOR")
M2MAUTHCONFIG_CID=$(eval "echo \$${ENV}_M2MAUTHCONFIG_CID")
M2MAUTHCONFIG_SECRET=$(eval "echo \$${ENV}_M2MAUTHCONFIG_SECRET")
M2MAUTHCONFIG_AUDIENCE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_AUDIENCE")
M2MAUTHCONFIG_AUTHDOMAIN=$(eval "echo \$${ENV}_M2MAUTHCONFIG_AUTHDOMAIN")
M2MAUTHCONFIG_TOKENEXPIRETIME=$(eval "echo \$${ENV}_M2MAUTHCONFIG_TOKENEXPIRETIME")
M2MAUTHCONFIG_USERID=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USERID")
M2MAUTHCONFIG_AUTHPROXYSERVERURL=$(eval "echo \$${ENV}_M2MAUTHCONFIG_AUTHPROXYSERVERURL")
M2MAUTHCONFIG_USERPROFILES_CREATE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USERPROFILES_CREATE")
M2MAUTHCONFIG_USERPROFILES_UPDATE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USERPROFILES_UPDATE")
M2MAUTHCONFIG_USERPROFILES_READ=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USERPROFILES_READ")
M2MAUTHCONFIG_USERPROFILES_DELETE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USERPROFILES_DELETE")
M2MAUTHCONFIG_USER2FA_CREATE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USER2FA_CREATE")
M2MAUTHCONFIG_USER2FA_UPDATE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USER2FA_UPDATE")
M2MAUTHCONFIG_USER2FA_READ=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USER2FA_READ")
M2MAUTHCONFIG_USER2FA_DELETE=$(eval "echo \$${ENV}_M2MAUTHCONFIG_USER2FA_DELETE")

DOMAIN=$(eval "echo \$${ENV}_DOMAIN")
SMTP=$(eval "echo \$${ENV}_SMTP")
DB_HOST_IP=$(eval "echo \$${ENV}_DB_HOST_IP")
LDAP_SERVER=$(eval "echo \$${ENV}_LDAP_SERVER")
REDIS_HOST=$(eval "echo \$${ENV}_REDIS_HOST")
AUTH_DB_HOST=$(eval "echo \$${ENV}_AUTH_DB_HOST")
AUTH0_NEW_DOMAIN=$(eval "echo \$${ENV}_AUTH0_NEW_DOMAIN")
AUTH0_DOMAIN=$(eval "echo \$${ENV}_AUTH0_DOMAIN")

SENDGRID_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID=$(eval "echo \$${ENV}_SENDGRID_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID")
SENDGRID_WELCOME_EMAIL_TEMPLATE_ID=$(eval "echo \$${ENV}_SENDGRID_WELCOME_EMAIL_TEMPLATE_ID")
SENDGRID_SELF_SERVICE_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID=$(eval "echo \$${ENV}_SENDGRID_SELF_SERVICE_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID")
SENDGRID_SELF_SERVICE_WELCOME_EMAIL_TEMPLATE_ID=$(eval "echo \$${ENV}_SENDGRID_SELF_SERVICE_WELCOME_EMAIL_TEMPLATE_ID")
SENDGRID_2FA_INVITATION_TEMPLATE_ID=$(eval "echo \$${ENV}_SENDGRID_2FA_INVITATION_TEMPLATE_ID")


if [[ -z "$ENV" ]] ; then
        echo "Environment should be set on startup with one of the below values"
        echo "ENV must be one of - DEV, QA, PROD or LOCAL"
        exit
fi

echo $DOMAIN
perl -pi -e "s/\{\{ENV_DOMAIN\}\}/$DOMAIN/g" $CONFFILENAME
echo $ENV
perl -pi -e "s/\{\{ENV\}\}/$ENV/g" $CONFFILENAME
echo $SMTP
perl -pi -e "s/\{\{ENV_SMTP\}\}/$SMTP/g" $CONFFILENAME
echo $DB_HOST_IP
perl -pi -e "s/\{\{DB_HOST_IP\}\}/$DB_HOST_IP/g" $CONFFILENAME
echo $LDAP_SERVER
perl -pi -e "s/\{\{LDAP_SERVER\}\}/$LDAP_SERVER/g" $CONFFILENAME
echo $REDIS_HOST
perl -pi -e "s/\{\{REDIS_HOST\}\}/$REDIS_HOST/g" $CONFFILENAME
echo $AUTH_DB_HOST
perl -pi -e "s/\{\{AUTH_DB_HOST\}\}/$AUTH_DB_HOST/g" $CONFFILENAME
echo $AUTH_SECRET
#echo ${AUTH_SECRET}
perl -pi -e "s/\{\{AUTH_SECRET\}\}/$AUTH_SECRET/g" $CONFFILENAME 
echo $DB_USER
perl -pi -e "s/\{\{DB_USER\}\}/$DB_USER/g" $CONFFILENAME 
echo $DB_PASSWORD
perl -pi -e "s/\{\{DB_PASSWORD\}\}/$DB_PASSWORD/g" $CONFFILENAME 
echo $LDAP_PASSWORD
perl -pi -e "s/\{\{LDAP_PASSWORD\}\}/$LDAP_PASSWORD/g" $CONFFILENAME 
echo $SG_API_KEY
perl -pi -e "s/\{\{SG_API_KEY\}\}/$SG_API_KEY/g" $CONFFILENAME 
echo $SG_TEMPLATEID
perl -pi -e "s/\{\{SG_TEMPLATEID\}\}/$SG_TEMPLATEID/g" $CONFFILENAME 
echo $SG_TEMPLATEID_PASSWORD
perl -pi -e "s/\{\{SG_TEMPLATEID_PASSWORD\}\}/$SG_TEMPLATEID_PASSWORD/g" $CONFFILENAME 
echo $AUTH0_ID
perl -pi -e "s/\{\{AUTH0_ID\}\}/$AUTH0_ID/g" $CONFFILENAME 
echo $AUTH0_ID_SECRET
perl -pi -e "s/\{\{AUTH0_ID_SECRET\}\}/$AUTH0_ID_SECRET/g" $CONFFILENAME 
echo $AUTH0_NONINTERACTIVE_ID
perl -pi -e "s/\{\{AUTH0_NONINTERACTIVE_ID\}\}/$AUTH0_NONINTERACTIVE_ID/g" $CONFFILENAME 
echo $AUTH0_NONINTERACTIVE_ID_SECRET
perl -pi -e "s/\{\{AUTH0_NONINTERACTIVE_ID_SECRET\}\}/$AUTH0_NONINTERACTIVE_ID_SECRET/g" $CONFFILENAME 
echo $AUTH0_NEW_ID
perl -pi -e "s/\{\{AUTH0_NEW_ID\}\}/$AUTH0_NEW_ID/g" $CONFFILENAME 
echo $AUTH0_NEW_ID_SECRET
perl -pi -e "s/\{\{AUTH0_NEW_ID_SECRET\}\}/$AUTH0_NEW_ID_SECRET/g" $CONFFILENAME 
echo $AUTH0_NEW_NONINTERACTIVE_ID
perl -pi -e "s/\{\{AUTH0_NEW_NONINTERACTIVE_ID\}\}/$AUTH0_NEW_NONINTERACTIVE_ID/g" $CONFFILENAME 
echo $AUTH0_NEW_NONINTERACTIVE_ID_SECRET
perl -pi -e "s/\{\{AUTH0_NEW_NONINTERACTIVE_ID_SECRET\}\}/$AUTH0_NEW_NONINTERACTIVE_ID_SECRET/g" $CONFFILENAME 
echo $DICEAUTH_DICE_URL
perl -pi -e "s/\{\{DICEAUTH_DICE_URL\}\}/$DICEAUTH_DICE_URL/g" $CONFFILENAME 
echo $DICEAUTH_API_KEY
perl -pi -e "s/\{\{DICEAUTH_API_KEY\}\}/$DICEAUTH_API_KEY/g" $CONFFILENAME 
echo $DICEAUTH_CREDDEFID
perl -pi -e "s/\{\{DICEAUTH_CREDDEFID\}\}/$DICEAUTH_CREDDEFID/g" $CONFFILENAME 
echo $ZENDESK_KEY
perl -pi -e "s/\{\{ZENDESK_KEY\}\}/$ZENDESK_KEY/g" $CONFFILENAME 
echo $ZENDESK_ID
perl -pi -e "s/\{\{ZENDESK_ID\}\}/$ZENDESK_ID/g" $CONFFILENAME 
echo $SERVICEACC01_CID
perl -pi -e "s/\{\{SERVICEACC01_CID\}\}/$SERVICEACC01_CID/g" $CONFFILENAME 
echo $SERVICEACC01_SECRET
perl -pi -e "s|\{\{SERVICEACC01_SECRET\}\}|$SERVICEACC01_SECRET|g" $CONFFILENAME 
echo $SERVICEACC01_UID
perl -pi -e "s/\{\{SERVICEACC01_UID\}\}/$SERVICEACC01_UID/g" $CONFFILENAME 
echo $SERVICEACC02_CID
perl -pi -e "s/\{\{SERVICEACC02_CID\}\}/$SERVICEACC02_CID/g" $CONFFILENAME 
echo $SERVICEACC02_SECRET
perl -pi -e "s|\{\{SERVICEACC02_SECRET\}\}|$SERVICEACC02_SECRET|g" $CONFFILENAME 
echo $SERVICEACC02_UID
perl -pi -e "s/\{\{SERVICEACC02_UID\}\}/$SERVICEACC02_UID/g" $CONFFILENAME 
echo $APP_PASSWORD
perl -pi -e "s/\{\{APP_PASSWORD\}\}/$APP_PASSWORD/g" $CONFFILENAME 
echo $APP_KEY
perl -pi -e "s/\{\{APP_KEY\}\}/$APP_KEY/g" $CONFFILENAME 
echo $APP_TOKEN
perl -pi -e "s/\{\{APP_TOKEN\}\}/$APP_TOKEN/g" $CONFFILENAME 
echo $AUTH_DB_USER
perl -pi -e "s/\{\{AUTH_DB_USER\}\}/$AUTH_DB_USER/g" $CONFFILENAME 
echo $AUTH_DB_PASSWORD
perl -pi -e "s/\{\{AUTH_DB_PASSWORD\}\}/$AUTH_DB_PASSWORD/g" $CONFFILENAME
echo $EVENTBUSSERVICE_ENDPOINT
#perl -pi -e "s/\{\{EVENTBUSSERVICE_ENDPOINT\}\}/$EVENTBUSSERVICE_ENDPOINT/g" $CONFFILENAME
perl -pi -e "s|\{\{EVENTBUSSERVICE_ENDPOINT\}\}|$EVENTBUSSERVICE_ENDPOINT|g" $CONFFILENAME
echo $EVENTBUSSERVICE_TOPIC
perl -pi -e "s/\{\{EVENTBUSSERVICE_TOPIC\}\}/$EVENTBUSSERVICE_TOPIC/g" $CONFFILENAME
echo $EVENTBUSSERVICE_ORIGINATOR
perl -pi -e "s/\{\{EVENTBUSSERVICE_ORIGINATOR\}\}/$EVENTBUSSERVICE_ORIGINATOR/g" $CONFFILENAME
echo $M2MAUTHCONFIG_CID
perl -pi -e "s/\{\{M2MAUTHCONFIG_CID\}\}/$M2MAUTHCONFIG_CID/g" $CONFFILENAME
echo $M2MAUTHCONFIG_SECRET
perl -pi -e "s/\{\{M2MAUTHCONFIG_SECRET\}\}/$M2MAUTHCONFIG_SECRET/g" $CONFFILENAME
echo $M2MAUTHCONFIG_AUDIENCE
#perl -pi -e "s/\{\{M2MAUTHCONFIG_AUDIENCE\}\}/$M2MAUTHCONFIG_AUDIENCE/g" $CONFFILENAME
perl -pi -e "s|\{\{M2MAUTHCONFIG_AUDIENCE\}\}|$M2MAUTHCONFIG_AUDIENCE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_AUTHDOMAIN
perl -pi -e "s/\{\{M2MAUTHCONFIG_AUTHDOMAIN\}\}/$M2MAUTHCONFIG_AUTHDOMAIN/g" $CONFFILENAME
echo $M2MAUTHCONFIG_TOKENEXPIRETIME
perl -pi -e "s/\{\{M2MAUTHCONFIG_TOKENEXPIRETIME\}\}/$M2MAUTHCONFIG_TOKENEXPIRETIME/g" $CONFFILENAME
echo $M2MAUTHCONFIG_USERID
perl -pi -e "s/\{\{M2MAUTHCONFIG_USERID\}\}/$M2MAUTHCONFIG_USERID/g" $CONFFILENAME
echo $M2MAUTHCONFIG_AUTHPROXYSERVERURL
#perl -pi -e "s/\{\{M2MAUTHCONFIG_AUTHPROXYSERVERURL\}\}/$M2MAUTHCONFIG_AUTHPROXYSERVERURL/g" $CONFFILENAME
perl -pi -e "s|\{\{M2MAUTHCONFIG_AUTHPROXYSERVERURL\}\}|$M2MAUTHCONFIG_AUTHPROXYSERVERURL|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USERPROFILES_CREATE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USERPROFILES_CREATE\}\}|$M2MAUTHCONFIG_USERPROFILES_CREATE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USERPROFILES_UPDATE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USERPROFILES_UPDATE\}\}|$M2MAUTHCONFIG_USERPROFILES_UPDATE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USERPROFILES_READ
perl -pi -e "s|\{\{M2MAUTHCONFIG_USERPROFILES_READ\}\}|$M2MAUTHCONFIG_USERPROFILES_READ|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USERPROFILES_DELETE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USERPROFILES_DELETE\}\}|$M2MAUTHCONFIG_USERPROFILES_DELETE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USER2FA_CREATE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USER2FA_CREATE\}\}|$M2MAUTHCONFIG_USER2FA_CREATE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USER2FA_UPDATE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USER2FA_UPDATE\}\}|$M2MAUTHCONFIG_USER2FA_UPDATE|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USER2FA_READ
perl -pi -e "s|\{\{M2MAUTHCONFIG_USER2FA_READ\}\}|$M2MAUTHCONFIG_USER2FA_READ|g" $CONFFILENAME
echo $M2MAUTHCONFIG_USER2FA_DELETE
perl -pi -e "s|\{\{M2MAUTHCONFIG_USER2FA_DELETE\}\}|$M2MAUTHCONFIG_USER2FA_DELETE|g" $CONFFILENAME
echo $AUTH0_NEW_DOMAIN
perl -pi -e "s/\{\{AUTH0_NEW_DOMAIN\}\}/$AUTH0_NEW_DOMAIN/g" $CONFFILENAME
echo $AUTH0_DOMAIN
perl -pi -e "s/\{\{AUTH0_DOMAIN\}\}/$AUTH0_DOMAIN/g" $CONFFILENAME
echo $SENDGRID_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID
perl -pi -e "s/\{\{SENDGRID_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID\}\}/$SENDGRID_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID/g" $CONFFILENAME
echo $SENDGRID_WELCOME_EMAIL_TEMPLATE_ID
perl -pi -e "s/\{\{SENDGRID_WELCOME_EMAIL_TEMPLATE_ID\}\}/$SENDGRID_WELCOME_EMAIL_TEMPLATE_ID/g" $CONFFILENAME
echo $SENDGRID_SELF_SERVICE_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID
perl -pi -e "s/\{\{SENDGRID_SELF_SERVICE_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID\}\}/$SENDGRID_SELF_SERVICE_RESEND_ACTIVATION_EMAIL_TEMPLATE_ID/g" $CONFFILENAME
echo $SENDGRID_SELF_SERVICE_WELCOME_EMAIL_TEMPLATE_ID
perl -pi -e "s/\{\{SENDGRID_SELF_SERVICE_WELCOME_EMAIL_TEMPLATE_ID\}\}/$SENDGRID_SELF_SERVICE_WELCOME_EMAIL_TEMPLATE_ID/g" $CONFFILENAME
echo $SENDGRID_2FA_INVITATION_TEMPLATE_ID
perl -pi -e "s/\{\{SENDGRID_2FA_INVITATION_TEMPLATE_ID\}\}/$SENDGRID_2FA_INVITATION_TEMPLATE_ID/g" $CONFFILENAME
